services:
  - type: web
    name: rauli-panaderia-app
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
