const LOCALE_OVERRIDES = {
  DO: "es-DO",
  ES: "es-ES",
  MX: "es-MX",
  AR: "es-AR",
  CL: "es-CL",
  CO: "es-CO",
  PE: "es-PE",
  VE: "es-VE",
  UY: "es-UY",
  PY: "es-PY",
  BO: "es-BO",
  EC: "es-EC",
  CR: "es-CR",
  GT: "es-GT",
  HN: "es-HN",
  NI: "es-NI",
  PA: "es-PA",
  SV: "es-SV",
  CU: "es-CU",
  PR: "es-PR",
  BR: "pt-BR",
  PT: "pt-PT",
  FR: "fr-FR",
  BE: "fr-BE",
  CA: "en-CA",
  US: "en-US",
  GB: "en-GB",
  AU: "en-AU",
  NZ: "en-NZ",
  IE: "en-IE",
  ZA: "en-ZA",
  DE: "de-DE",
  AT: "de-AT",
  CH: "de-CH",
  IT: "it-IT",
  NL: "nl-NL",
  RU: "ru-RU",
  CN: "zh-CN",
  TW: "zh-TW",
  JP: "ja-JP",
  KR: "ko-KR",
  IN: "en-IN",
  SA: "ar-SA",
  AE: "ar-AE",
  EG: "ar-EG"
};

const COUNTRY_DATA = [
  { id: "AF", label: "Afganistán", currency: "AFN" },
  { id: "AL", label: "Albania", currency: "ALL" },
  { id: "DZ", label: "Argelia", currency: "DZD" },
  { id: "AD", label: "Andorra", currency: "EUR" },
  { id: "AO", label: "Angola", currency: "AOA" },
  { id: "AG", label: "Antigua y Barbuda", currency: "XCD" },
  { id: "AR", label: "Argentina", currency: "ARS" },
  { id: "AM", label: "Armenia", currency: "AMD" },
  { id: "AU", label: "Australia", currency: "AUD" },
  { id: "AT", label: "Austria", currency: "EUR" },
  { id: "AZ", label: "Azerbaiyán", currency: "AZN" },
  { id: "BS", label: "Bahamas", currency: "BSD" },
  { id: "BH", label: "Baréin", currency: "BHD" },
  { id: "BD", label: "Bangladés", currency: "BDT" },
  { id: "BB", label: "Barbados", currency: "BBD" },
  { id: "BY", label: "Bielorrusia", currency: "BYN" },
  { id: "BE", label: "Bélgica", currency: "EUR" },
  { id: "BZ", label: "Belice", currency: "BZD" },
  { id: "BJ", label: "Benín", currency: "XOF" },
  { id: "BT", label: "Bután", currency: "BTN" },
  { id: "BO", label: "Bolivia", currency: "BOB" },
  { id: "BA", label: "Bosnia y Herzegovina", currency: "BAM" },
  { id: "BW", label: "Botsuana", currency: "BWP" },
  { id: "BR", label: "Brasil", currency: "BRL" },
  { id: "BN", label: "Brunéi", currency: "BND" },
  { id: "BG", label: "Bulgaria", currency: "BGN" },
  { id: "BF", label: "Burkina Faso", currency: "XOF" },
  { id: "BI", label: "Burundi", currency: "BIF" },
  { id: "CV", label: "Cabo Verde", currency: "CVE" },
  { id: "KH", label: "Camboya", currency: "KHR" },
  { id: "CM", label: "Camerún", currency: "XAF" },
  { id: "CA", label: "Canadá", currency: "CAD" },
  { id: "CF", label: "República Centroafricana", currency: "XAF" },
  { id: "TD", label: "Chad", currency: "XAF" },
  { id: "CL", label: "Chile", currency: "CLP" },
  { id: "CN", label: "China", currency: "CNY" },
  { id: "CO", label: "Colombia", currency: "COP" },
  { id: "KM", label: "Comoras", currency: "KMF" },
  { id: "CG", label: "República del Congo", currency: "XAF" },
  { id: "CD", label: "República Democrática del Congo", currency: "CDF" },
  { id: "CR", label: "Costa Rica", currency: "CRC" },
  { id: "CI", label: "Côte d'Ivoire", currency: "XOF" },
  { id: "HR", label: "Croacia", currency: "EUR" },
  { id: "CU", label: "Cuba", currency: "CUP" },
  { id: "CY", label: "Chipre", currency: "EUR" },
  { id: "CZ", label: "Chequia", currency: "CZK" },
  { id: "DK", label: "Dinamarca", currency: "DKK" },
  { id: "DJ", label: "Yibuti", currency: "DJF" },
  { id: "DM", label: "Dominica", currency: "XCD" },
  { id: "DO", label: "República Dominicana", currency: "DOP" },
  { id: "EC", label: "Ecuador", currency: "USD" },
  { id: "EG", label: "Egipto", currency: "EGP" },
  { id: "SV", label: "El Salvador", currency: "USD" },
  { id: "GQ", label: "Guinea Ecuatorial", currency: "XAF" },
  { id: "ER", label: "Eritrea", currency: "ERN" },
  { id: "EE", label: "Estonia", currency: "EUR" },
  { id: "SZ", label: "Esuatini", currency: "SZL" },
  { id: "ET", label: "Etiopía", currency: "ETB" },
  { id: "FJ", label: "Fiyi", currency: "FJD" },
  { id: "FI", label: "Finlandia", currency: "EUR" },
  { id: "FR", label: "Francia", currency: "EUR" },
  { id: "GA", label: "Gabón", currency: "XAF" },
  { id: "GM", label: "Gambia", currency: "GMD" },
  { id: "GE", label: "Georgia", currency: "GEL" },
  { id: "DE", label: "Alemania", currency: "EUR" },
  { id: "GH", label: "Ghana", currency: "GHS" },
  { id: "GR", label: "Grecia", currency: "EUR" },
  { id: "GD", label: "Granada", currency: "XCD" },
  { id: "GT", label: "Guatemala", currency: "GTQ" },
  { id: "GN", label: "Guinea", currency: "GNF" },
  { id: "GW", label: "Guinea-Bisáu", currency: "XOF" },
  { id: "GY", label: "Guyana", currency: "GYD" },
  { id: "HT", label: "Haití", currency: "HTG" },
  { id: "HN", label: "Honduras", currency: "HNL" },
  { id: "HU", label: "Hungría", currency: "HUF" },
  { id: "IS", label: "Islandia", currency: "ISK" },
  { id: "IN", label: "India", currency: "INR" },
  { id: "ID", label: "Indonesia", currency: "IDR" },
  { id: "IR", label: "Irán", currency: "IRR" },
  { id: "IQ", label: "Irak", currency: "IQD" },
  { id: "IE", label: "Irlanda", currency: "EUR" },
  { id: "IL", label: "Israel", currency: "ILS" },
  { id: "IT", label: "Italia", currency: "EUR" },
  { id: "JM", label: "Jamaica", currency: "JMD" },
  { id: "JP", label: "Japón", currency: "JPY" },
  { id: "JO", label: "Jordania", currency: "JOD" },
  { id: "KZ", label: "Kazajistán", currency: "KZT" },
  { id: "KE", label: "Kenia", currency: "KES" },
  { id: "KI", label: "Kiribati", currency: "AUD" },
  { id: "KP", label: "Corea del Norte", currency: "KPW" },
  { id: "KR", label: "Corea del Sur", currency: "KRW" },
  { id: "KW", label: "Kuwait", currency: "KWD" },
  { id: "KG", label: "Kirguistán", currency: "KGS" },
  { id: "LA", label: "Laos", currency: "LAK" },
  { id: "LV", label: "Letonia", currency: "EUR" },
  { id: "LB", label: "Líbano", currency: "LBP" },
  { id: "LS", label: "Lesoto", currency: "LSL" },
  { id: "LR", label: "Liberia", currency: "LRD" },
  { id: "LY", label: "Libia", currency: "LYD" },
  { id: "LI", label: "Liechtenstein", currency: "CHF" },
  { id: "LT", label: "Lituania", currency: "EUR" },
  { id: "LU", label: "Luxemburgo", currency: "EUR" },
  { id: "MG", label: "Madagascar", currency: "MGA" },
  { id: "MW", label: "Malaui", currency: "MWK" },
  { id: "MY", label: "Malasia", currency: "MYR" },
  { id: "MV", label: "Maldivas", currency: "MVR" },
  { id: "ML", label: "Malí", currency: "XOF" },
  { id: "MT", label: "Malta", currency: "EUR" },
  { id: "MH", label: "Islas Marshall", currency: "USD" },
  { id: "MR", label: "Mauritania", currency: "MRU" },
  { id: "MU", label: "Mauricio", currency: "MUR" },
  { id: "MX", label: "México", currency: "MXN" },
  { id: "FM", label: "Micronesia", currency: "USD" },
  { id: "MD", label: "Moldavia", currency: "MDL" },
  { id: "MC", label: "Mónaco", currency: "EUR" },
  { id: "MN", label: "Mongolia", currency: "MNT" },
  { id: "ME", label: "Montenegro", currency: "EUR" },
  { id: "MA", label: "Marruecos", currency: "MAD" },
  { id: "MZ", label: "Mozambique", currency: "MZN" },
  { id: "MM", label: "Myanmar", currency: "MMK" },
  { id: "NA", label: "Namibia", currency: "NAD" },
  { id: "NR", label: "Nauru", currency: "AUD" },
  { id: "NP", label: "Nepal", currency: "NPR" },
  { id: "NL", label: "Países Bajos", currency: "EUR" },
  { id: "NZ", label: "Nueva Zelanda", currency: "NZD" },
  { id: "NI", label: "Nicaragua", currency: "NIO" },
  { id: "NE", label: "Níger", currency: "XOF" },
  { id: "NG", label: "Nigeria", currency: "NGN" },
  { id: "MK", label: "Macedonia del Norte", currency: "MKD" },
  { id: "NO", label: "Noruega", currency: "NOK" },
  { id: "OM", label: "Omán", currency: "OMR" },
  { id: "PK", label: "Pakistán", currency: "PKR" },
  { id: "PW", label: "Palaos", currency: "USD" },
  { id: "PA", label: "Panamá", currency: "USD" },
  { id: "PG", label: "Papúa Nueva Guinea", currency: "PGK" },
  { id: "PY", label: "Paraguay", currency: "PYG" },
  { id: "PE", label: "Perú", currency: "PEN" },
  { id: "PH", label: "Filipinas", currency: "PHP" },
  { id: "PL", label: "Polonia", currency: "PLN" },
  { id: "PT", label: "Portugal", currency: "EUR" },
  { id: "QA", label: "Catar", currency: "QAR" },
  { id: "RO", label: "Rumanía", currency: "RON" },
  { id: "RU", label: "Rusia", currency: "RUB" },
  { id: "RW", label: "Ruanda", currency: "RWF" },
  { id: "KN", label: "San Cristóbal y Nieves", currency: "XCD" },
  { id: "LC", label: "Santa Lucía", currency: "XCD" },
  { id: "VC", label: "San Vicente y las Granadinas", currency: "XCD" },
  { id: "WS", label: "Samoa", currency: "WST" },
  { id: "SM", label: "San Marino", currency: "EUR" },
  { id: "ST", label: "Santo Tomé y Príncipe", currency: "STN" },
  { id: "SA", label: "Arabia Saudita", currency: "SAR" },
  { id: "SN", label: "Senegal", currency: "XOF" },
  { id: "RS", label: "Serbia", currency: "RSD" },
  { id: "SC", label: "Seychelles", currency: "SCR" },
  { id: "SL", label: "Sierra Leona", currency: "SLL" },
  { id: "SG", label: "Singapur", currency: "SGD" },
  { id: "SK", label: "Eslovaquia", currency: "EUR" },
  { id: "SI", label: "Eslovenia", currency: "EUR" },
  { id: "SB", label: "Islas Salomón", currency: "SBD" },
  { id: "SO", label: "Somalia", currency: "SOS" },
  { id: "ZA", label: "Sudáfrica", currency: "ZAR" },
  { id: "SS", label: "Sudán del Sur", currency: "SSP" },
  { id: "ES", label: "España", currency: "EUR" },
  { id: "LK", label: "Sri Lanka", currency: "LKR" },
  { id: "SD", label: "Sudán", currency: "SDG" },
  { id: "SR", label: "Surinam", currency: "SRD" },
  { id: "SE", label: "Suecia", currency: "SEK" },
  { id: "CH", label: "Suiza", currency: "CHF" },
  { id: "SY", label: "Siria", currency: "SYP" },
  { id: "TW", label: "Taiwán", currency: "TWD" },
  { id: "TJ", label: "Tayikistán", currency: "TJS" },
  { id: "TZ", label: "Tanzania", currency: "TZS" },
  { id: "TH", label: "Tailandia", currency: "THB" },
  { id: "TL", label: "Timor Oriental", currency: "USD" },
  { id: "TG", label: "Togo", currency: "XOF" },
  { id: "TO", label: "Tonga", currency: "TOP" },
  { id: "TT", label: "Trinidad y Tobago", currency: "TTD" },
  { id: "TN", label: "Túnez", currency: "TND" },
  { id: "TR", label: "Turquía", currency: "TRY" },
  { id: "TM", label: "Turkmenistán", currency: "TMT" },
  { id: "TV", label: "Tuvalu", currency: "AUD" },
  { id: "UG", label: "Uganda", currency: "UGX" },
  { id: "UA", label: "Ucrania", currency: "UAH" },
  { id: "AE", label: "Emiratos Árabes Unidos", currency: "AED" },
  { id: "GB", label: "Reino Unido", currency: "GBP" },
  { id: "US", label: "Estados Unidos", currency: "USD" },
  { id: "UY", label: "Uruguay", currency: "UYU" },
  { id: "UZ", label: "Uzbekistán", currency: "UZS" },
  { id: "VU", label: "Vanuatu", currency: "VUV" },
  { id: "VA", label: "Ciudad del Vaticano", currency: "EUR" },
  { id: "VE", label: "Venezuela", currency: "VES" },
  { id: "VN", label: "Vietnam", currency: "VND" },
  { id: "YE", label: "Yemen", currency: "YER" },
  { id: "ZM", label: "Zambia", currency: "ZMW" },
  { id: "ZW", label: "Zimbabue", currency: "ZWL" },
  { id: "PS", label: "Palestina", currency: "ILS" },
  { id: "XK", label: "Kosovo", currency: "EUR" }
];

const MULTI_CURRENCY = {
  CU: ["CUP", "MLC", "USD"],
  EC: ["USD"],
  SV: ["USD"],
  PA: ["USD"],
  FM: ["USD"],
  MH: ["USD"],
  PW: ["USD"],
  TL: ["USD"],
  US: ["USD"],
  PR: ["USD"],
  DO: ["DOP", "USD"],
  VE: ["VES", "USD"],
  AR: ["ARS", "USD"],
  BO: ["BOB", "USD"],
  UY: ["UYU", "USD"],
  PY: ["PYG", "USD"],
  MX: ["MXN", "USD"],
  PE: ["PEN", "USD"],
  GT: ["GTQ", "USD"],
  HN: ["HNL", "USD"],
  NI: ["NIO", "USD"],
  CR: ["CRC", "USD"],
  CO: ["COP", "USD"],
  CL: ["CLP", "USD"]
};

export const COUNTRIES = COUNTRY_DATA
  .map((country) => {
    const currencies = MULTI_CURRENCY[country.id] || [country.currency];
    return {
      ...country,
      currency: currencies[0],
      currencies,
      locale: LOCALE_OVERRIDES[country.id] || "en-US"
    };
  })
  .sort((a, b) => a.label.localeCompare(b.label, "es"));

const COUNTRY_BY_CODE = new Map(COUNTRIES.map((c) => [c.id, c]));

export const getCountryByCode = (code) => COUNTRY_BY_CODE.get((code || "").toUpperCase());

export const formatCountryOption = (country) => `${country.label} (${country.id})`;

export const findCountryByInput = (value) => {
  const raw = (value || "").trim();
  if (!raw) return null;
  const codeMatch = raw.match(/\(([A-Z]{2})\)$/);
  const code = codeMatch ? codeMatch[1] : raw.toUpperCase();
  if (COUNTRY_BY_CODE.has(code)) return COUNTRY_BY_CODE.get(code);
  const lowered = raw.toLowerCase();
  return COUNTRIES.find((c) => c.label.toLowerCase() === lowered) || null;
};
